# Generated by Django 4.2.7 on 2023-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("artist", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "album",
                "managed": False,
            },
        ),
    ]
